In [18]:
!python -u main.py --input_path "./data/shuffled_new_data_25k.npz" --out_dir ./ --name ALLAML --method GRACES --epochs 100 --n_splits 3 --n_trials 20 --n_jobs 5 --seed 57 --patience 10 --is_snp 0 --validation_split 0.2 --min_delta 0.0 --lr_min 1e-05 --lr_max 0.1 --dropout_min 0.2 --dropout_max 0.8 --weight_decay_min 0.0 --weight_decay_max 0.1 --alpha_min 0.8 --alpha_max 0.99 --task_type regression --selected_activate sigmoid --eval_metric loss --batch_size_list 8,16,32 --digits_list 100,200,500 --f_correct_list 0,0.1,0.5,0.9 --do_parameter_search 1

2025-11-18 18:12:36,339 - INFO - [LOG] writing to /Users/zz/Uni of Auckland Dropbox/project-qym/docker/mini-server_test/pipeline_GRACES_1_0.log
2025-11-18 18:12:36,340 - INFO - Starting pipeline...
2025-11-18 18:12:36,340 - INFO - Starting pipeline...
2025-11-18 18:12:36,340 - INFO - The number of CPU: 1
2025-11-18 18:12:36,342 - INFO - folder /Users/zz/Uni of Auckland Dropbox/project-qym/docker/mini-server_test/pipeline/GRACES_ALLAML_sigmoid exists, deleting...
2025-11-18 18:12:36,344 - INFO - folder /Users/zz/Uni of Auckland Dropbox/project-qym/docker/mini-server_test/pipeline/GRACES_ALLAML_sigmoid deleted
2025-11-18 18:12:36,344 - INFO - folder /Users/zz/Uni of Auckland Dropbox/project-qym/docker/mini-server_test/pipeline/GRACES_ALLAML_sigmoid created
2025-11-18 18:12:36,344 - INFO - Processing the dataset ALLAML
2025-11-18 18:12:36,406 - INFO - Your file only contains x_train / y_train, we will not perform data splitting,So we can only perform feature selection and cannot conduct f

In [19]:
import numpy as np
original = np.load("./data/shuffled_new_data_25k.npz")
all_variables = np.array([int(i) for i in original['causal_new']])
res = np.load("./GRACES_ALLAML_sigmoid/GRACES_ALLAML_idx.npy")

np.isin(all_variables,res).sum()

21

In [20]:
!python -u main.py --input_path "./data/shuffled_new_data_50k.npz" --out_dir ./ --name ALLAML_50 --method GRACES --epochs 100 --n_splits 3 --n_trials 20 --n_jobs 5 --seed 57 --patience 10 --is_snp 0 --validation_split 0.2 --min_delta 0.0 --lr_min 1e-05 --lr_max 0.1 --dropout_min 0.2 --dropout_max 0.8 --weight_decay_min 0.0 --weight_decay_max 0.1 --alpha_min 0.8 --alpha_max 0.99 --task_type regression --selected_activate sigmoid --eval_metric loss --batch_size_list 8,16,32 --digits_list 100,200,500 --f_correct_list 0,0.1,0.5,0.9 --do_parameter_search 1

2025-11-18 18:41:36,949 - INFO - [LOG] writing to /Users/zz/Uni of Auckland Dropbox/project-qym/docker/mini-server_test/pipeline_GRACES_1_0.log
2025-11-18 18:41:36,949 - INFO - Starting pipeline...
2025-11-18 18:41:36,949 - INFO - Starting pipeline...
2025-11-18 18:41:36,949 - INFO - The number of CPU: 1
2025-11-18 18:41:36,951 - INFO - folder /Users/zz/Uni of Auckland Dropbox/project-qym/docker/mini-server_test/pipeline/GRACES_ALLAML_50_sigmoid exists, deleting...
2025-11-18 18:41:36,952 - INFO - folder /Users/zz/Uni of Auckland Dropbox/project-qym/docker/mini-server_test/pipeline/GRACES_ALLAML_50_sigmoid deleted
2025-11-18 18:41:36,952 - INFO - folder /Users/zz/Uni of Auckland Dropbox/project-qym/docker/mini-server_test/pipeline/GRACES_ALLAML_50_sigmoid created
2025-11-18 18:41:36,953 - INFO - Processing the dataset ALLAML_50
2025-11-18 18:41:37,076 - INFO - Your file only contains x_train / y_train, we will not perform data splitting,So we can only perform feature selection and cann

In [21]:
import numpy as np
original = np.load("./data/shuffled_new_data_50k.npz")
all_variables_50 = np.array([int(i) for i in original['causal_new']])

res_50 = np.load("./GRACES_ALLAML_50_sigmoid/GRACES_ALLAML_50_idx.npy")
np.isin(all_variables_50,res_50).sum()

13

In [3]:
import numpy as np

# ====================
# 读取数据
# ====================
data = np.load("./data/data_50k.npz")
X = data['x_train']
Y = data['y_train']

# ====================
# 随机打乱特征顺序
# ====================
n_features = X.shape[1]
shuffled_order = np.random.permutation(n_features)
X_shuffled = X[:, shuffled_order]

# ====================
# 原始 causal variants
# ====================
all_variables = np.array([
    100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200, 
    1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000, 2100, 2200, 
    2300, 2400, 13000,13100,13200,13300,13400,13500,13600,13700,
    13800,13900,14000,14100,14200,14300,14400,14500,14600,14700,
    14800,14900,15000,15100,15200,15300
])

# ====================
# 生成反向映射（原 index → 新 index）
# ====================
inverse_map = np.zeros(n_features, dtype=int)
inverse_map[shuffled_order] = np.arange(n_features)

# ====================
# 更新 causal 列索引
# ====================
all_variables_new = inverse_map[all_variables]

print("新的 causal indices:", all_variables_new)




新的 causal indices: [ 9357 20406 25799 21398 49632 24776 31572 12456 21695 34718 43794 35766
 42808 36436  9494 15813 14984 23585 40091 34949  8006 43101 26815 40616
 31267  1505 14420 30719 39832 33610 12210 19642 30857 25855  3179 10564
 21192 48926 10950 33842 15638 28170 16562 35551 14878 38284 22117 29753]


In [4]:
np.savez("./data/shuffled_new_data_50k.npz",
         x_train=X_shuffled,
         y_train=Y,
         shuffled_order=shuffled_order,
         causal_new=all_variables_new)

方差为 0 的特征数目： 0


array([0.9994097 , 1.0048767 , 1.0470843 , ..., 0.29897836, 0.4626575 ,
       0.41386035], dtype=float32)

In [38]:
same = np.all(X == X[0], axis=1)
all_same = np.all(same)

print("是否所有样本完全一致？", all_same)

是否所有样本完全一致？ False


In [16]:
sam = np.array([i for i in range(1920)])
sam2 = np.array([i for i in range(1930,2000)])
sam = np.concatenate((sam,sam2))

In [20]:
X[sam,0]

array([-0.04286699, -0.2737042 , -1.2852892 , ..., -1.3034146 ,
        0.41858876,  1.0452573 ], dtype=float32)

In [3]:
data = np.load("./data/data_50k.npz")

In [4]:
X = data['x_train']
Y = data['y_train']

In [10]:
X[1929,30000:51925]

array([0., 0., 1., ..., 0., 1., 1.], dtype=float32)

In [7]:
X.shape

(2000, 51926)

In [ ]:
!python -u main.py --input_path "./data/data_100k.npz" --out_dir ./ --name ALLAML_100 --method GRACES --epochs 100 --n_splits 5 --n_trials 20 --n_jobs 4 --seed 42 --patience 10 --is_snp 0 --validation_split 0.2 --min_delta 0.0 --lr_min 1e-05 --lr_max 0.1 --dropout_min 0.2 --dropout_max 0.8 --weight_decay_min 0.0 --weight_decay_max 0.1 --alpha_min 0.8 --alpha_max 0.99 --task_type regression --selected_activate sigmoid --eval_metric loss --batch_size_list 8,16,32 --digits_list 100,200,500 --f_correct_list 0,0.1,0.5,0.9 --do_parameter_search 1

2025-11-12 19:50:47,569 - INFO - [LOG] writing to /Users/zz/Uni of Auckland Dropbox/project-qym/docker/mini-server_test/pipeline_GRACES_1_0.log
2025-11-12 19:50:47,569 - INFO - Starting pipeline...
2025-11-12 19:50:47,569 - INFO - Starting pipeline...
2025-11-12 19:50:47,569 - INFO - The number of CPU: 1
2025-11-12 19:50:47,572 - INFO - folder /Users/zz/Uni of Auckland Dropbox/project-qym/docker/mini-server_test/pipeline/GRACES_ALLAML_100_sigmoid created
2025-11-12 19:50:47,572 - INFO - Processing the dataset ALLAML_100
2025-11-12 19:50:47,812 - INFO - Your file only contains x_train / y_train, we will not perform data splitting,So we can only perform feature selection and cannot conduct final evaluation. Default use_evaluation=0.
[auto] detected float-continuous -> regression (train range -3.3540~3.2178)
2025-11-12 19:50:47,814 - INFO - The number of classes 1
2025-11-12 19:50:47,814 - INFO - [Regression] train range: -3.3540 ~ 3.2178
2025-11-12 19:50:47,814 - INFO - [Split] name=ALLA

In [23]:
!python run_all_commands.py

[INFO] Total runs: 13
[INFO] Logs directory: /Users/zz/Uni of Auckland Dropbox/project-qym/docker/mini-server_test/pipeline/run_logs
[INFO] Summary CSV: /Users/zz/Uni of Auckland Dropbox/project-qym/docker/mini-server_test/pipeline/run_logs/runs_summary.csv
--------------------------------------------------------------------------------
[RUN 001] EARFS | D_search_Eval
  CMD: python main.py --input_path ./data/ALLAML_10.npz --name ALLAML --method EARFS --is_snp 0 --do_parameter_search 1 --n_trials 2 --n_jobs 2 --eval_metric loss --use_evaluation 1 --max_features 4 --feature_step 2 --max_features_graces 6
  -> returncode=0, duration=2.8s, out=001_EARFS_D_search_Eval.out.txt, err=001_EARFS_D_search_Eval.err.txt
--------------------------------------------------------------------------------
[RUN 002] CANCELOUT | D_search_Eval
  CMD: python main.py --input_path ./data/ALLAML_10.npz --name ALLAML --method CANCELOUT --is_snp 0 --do_parameter_search 1 --n_trials 2 --n_jobs 2 --eval_metric los

In [19]:
CORE_METHODS = ["EARFS","CANCELOUT","GRACES"]
INTERP_METHODS = ["FeatureAblation","Occlusion","Lime","DeepLIFT","GradientShap","LRP"]
OTHER_METHODS = ["BCOR","LASSO","FTEST","RF"]
methods = CORE_METHODS + INTERP_METHODS + OTHER_METHODS


In [20]:
import numpy as np
for method in methods:
    if method in INTERP_METHODS:
        res_path = f"./result/{method}_ALLAML_relu/{method}_ALLAML_0_idx.npy"
    elif method =="LASSO":
        res_path = f"./result/{method}_ALLAML_relu/{method}_ALLAML_idx.npz"
    else:
        res_path = f"./result/{method}_ALLAML_relu/{method}_ALLAML_idx.npy"
    try:
        idx = np.load(res_path)
        if method =="LASSO":
            idx = idx['coefs']
        print(f"{method}: {idx.shape}")
    except:
        print(f"{method}: No result found")

EARFS: No result found
CANCELOUT: No result found
GRACES: No result found
FeatureAblation: No result found
Occlusion: No result found
Lime: No result found
DeepLIFT: No result found
GradientShap: No result found
LRP: No result found
BCOR: No result found
LASSO: No result found
FTEST: No result found
RF: No result found


In [3]:
method = "EARFS"
res_path = f"./result/EARFS_ALLAML_relu/EARFS_ALLAML_results.npz"

In [6]:
idx = np.load(res_path,allow_pickle=True)

In [24]:
import numpy as np

CORE_METHODS = ["EARFS","CANCELOUT","GRACES"]
INTERP_METHODS = ["FeatureAblation","Occlusion","Lime","DeepLIFT","GradientShap","LRP"]
OTHER_METHODS = ["BCOR","LASSO","FTEST","RF"]
methods = CORE_METHODS + INTERP_METHODS + OTHER_METHODS


for method in methods:
    if method in INTERP_METHODS:
        res_path = f"./result/{method}_ALLAML_relu/{method}_ALLAML_results.npz"
    elif method =="LASSO":
        res_path = f"./result/{method}_ALLAML_relu/{method}_ALLAML_results.npz"
    else:
        res_path = f"./result/{method}_ALLAML_relu/{method}_ALLAML_results.npz"
    try:
        idx = np.load(res_path,allow_pickle=True)
        print(f"{method}: {idx['test_results']}")
    except:
        print(f"{method}: No result found")

EARFS: [[0.]
 [0.]]
CANCELOUT: [[0.76]
 [0.8 ]]
GRACES: [[0.5]
 [0.8]]
FeatureAblation: [[0.82]
 [1.  ]]
Occlusion: [[0.7]
 [0.7]]
Lime: [[0.76]
 [0.64]]
DeepLIFT: [[0.86]
 [0.98]]
GradientShap: [[0.82]
 [1.  ]]
LRP: [[0.86]
 [1.  ]]
BCOR: [[1.]
 [1.]]
LASSO: [[1.  ]
 [0.98]]
FTEST: [[0.99]
 [1.  ]]
RF: [[1.]
 [1.]]


In [8]:
list(idx.keys())

['test_results',
 'cv_val_losses',
 'weights',
 'indices',
 'best_params',
 'mean_test_results',
 'std_test_results',
 'mean_cv_val_losses',
 'std_cv_val_losses',
 'feature_sequence',
 'total_features',
 'max_features',
 'n_steps',
 'seeds',
 'config',
 'timestamp',
 'per_step_report_metrics']